
# values.yaml
replicaCount: 1

image:
  repository: myapp
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /

# Add additional configuration parameters as needed for your specific application.
